### PR TITLE
Exclude netcdf-src from default members

### PR DESCRIPTION
**Pull request by magnusuMET**
Thanks @aldanor for this trick!

### CODE REVIEW

**Comment by magnusuMET** [comment]
@aldanor This trick does not work like we hoped it would. Since we use path dependencies `netcdf-src` (and `hdf5-src`) will also be members of the default members.
 > All path dependencies residing in the workspace directory automatically become members. 
https://doc.rust-lang.org/cargo/reference/workspaces.html

We don't see this error in `hdf5` since we always pull in the submodule

**Comment by aldanor** [comment]
> We don't see this error in hdf5 since we always pull in the submodule

Hm, what do you mean?

**Comment by magnusuMET** [comment]
@aldanor It seems I've gotten a bit confused with the meaning of `--workspace`, which is not necessary when they are explicitely placed in `[workspace]`. Specifying `--workspace` and `default_members` overrides `default_members`, causing `netcdf-src` to be built in this build.

**Comment by aldanor** [comment]
> @aldanor It seems I've gotten a bit confused with the meaning of --workspace, which is not necessary when they are explicitely placed in [workspace]. Specifying --workspace and default_members overrides default_members, causing netcdf-src to be built in this build.

Yea, that's kind of the meaning here, "what should cargo commands point at when you didn't specify `--workspace` at all". Glad it worked out :)

**Pull request merged**
